[metadata]
name = pytest-persistence
version = 0.1.11
description = Pytest plugin for persistent objects
author = Jakub Urban
author_email = kubo.urban@gmail.com
maintainer = Matej Dujava
maintainer_email = mdujava@redhat.com
url = https://github.com/3scale-qe/pytest-persistence
long_description = file: README.md
license = Apache-2.0
license_files = LICENSE
classifiers =
    Operating System :: OS Independent
    Intended Audience :: Developers
    Framework :: Pytest
    Programming Language :: Python :: 3

[options]
packages = pytest_persistence
install_requires =
    pytest

[options.entry_points]
pytest11 =
    persistence = pytest_persistence.plugin

[flake8]
max-line-length = 120
ignore = E203,W503

[mypy]
ignore_missing_imports = True
check_untyped_defs = true
local_partial_types = true
