[metadata]
name = pytest-persistence
version = 0.1.11
description = Pytest plugin for persistent objects
author = Jakub Urban
author_email = kubo.urban@gmail.com
maintainer = Matej Dujava
maintainer_email = mdujava@redhat.com
url = https://github.com/3scale-qe/pytest-persistence
long_description = file: README.md
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Framework :: Pytest
    Operating System :: OS Independent
    License :: OSI Approved :: MIT License

[options]
packages = pytest_persistence

[options.entry_points]
pytest11 =
    persistence = pytest_persistence.plugin
