[tox]
envlist = py-pytest{744,800,840,-latest}

[testenv]
deps =
	pytest744: pytest==7.4.4
	pytest800: pytest==8.0.0
	pytest840: pytest==8.4.0
	pytest-latest: pytest
	pytest-xdist
commands =
	pip install -e .
	pytest tests/test_unit.py tests/test_plugin.py
