[tox]
envlist = py{311,312,313,314}-pytest{744,800,840,-latest}

[gh-actions]
python =
    3.14: py314
    3.13: py313
    3.12: py312
    3.11: py311

[testenv]
deps =
	pytest744: pytest==7.4.4
	pytest800: pytest==8.0.0
	pytest840: pytest==8.4.0
	pytest-latest: pytest
	pytest-xdist
commands =
	pip install -e .
	pytest tests/test_unit.py tests/test_plugin.py
